### ISSUE TITLE
Request to publish a version to dockerhub

### ISSUE THREAD

**Issue by harlantwood** [guillemcordoba/holochain-rsm-docker#2]
Elemental chat currently rests on holochain ref [60da73e79397cbe21280edf9a3062ae325f0bf9a](https://github.com/holochain/holochain/commit/60da73e79397cbe21280edf9a3062ae325f0bf9a) (short: `60da73e`)

Could you push a version with this ref to dockerhub?

(I suspect that I could just build it locally instead, or create an account on dockerhub and push it there myself, but my docker fu is limited...)

**Comment by harlantwood** [comment]
@guillemcordoba

**Comment by guillemcordoba** [comment]
Yeah right, I'll try to. Although holochain core development is moving so fast with so many changes that it might be better for you to start working in a linux docker image... Nix does facilitate the dev experience a lot! And more so with the coming tooling changes (dna_util doesn't exist anymore, etc.).

**Comment by guillemcordoba** [comment]
Here you are: https://hub.docker.com/layers/guillemcordoba/rsm/60da73e/images/sha256-12f07e24caf6c5f579fd8dfb48429e8919d8be8e610b8819bd3beddc9762ad83?context=explore
