### ISSUE TITLE
How is this different from the docker images created by https://github.com/holochain/holochain ?

### ISSUE THREAD

**Issue by harlantwood** [guillemcordoba/holochain-rsm-docker#3]
In https://github.com/holochain/holochain/blob/develop/.circleci/config.yml we use scripts/dockerfiles from https://github.com/holochain/holochain/tree/develop/docker to create docker images: https://hub.docker.com/r/holochain/holochain/tags?page=1&ordering=last_updated

One difference I notice that these use nix, and the Dockerfile in this repo does not.

Curious about when each kind of docker image (created from this repo vs those referred to above) is useful.  Thanks for any insights!

@guillemcordoba

**Comment by guillemcordoba** [comment]
Yeah so the docker images built from the holochain repository actually don't contain the holochain binaries. They are used only for CI testing of holochain core itself. So this is what the image in this repo is doing, packaing the holochain binaries for you.

**Comment by harlantwood** [comment]
Thanks, got it.
